version: '3.7'
services:
  php:
    build: ./docker/php
    ports: ['9000:9001']
    volumes:
      - ./symfony/:/var/www/symfony:cached
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony/:/var/www/symfony:cached